### ISSUE TITLE
Please link to your website from the repo

### ISSUE THREAD

**Issue by sofer** [iuliaL/Portfolio#6]
Thank you.

**Comment by iuliaL** [comment]
http://iulial.github.io/Portfolio/

The thing is this page is 11 months old and I was thinking that I maybe apply with a new github pages hosted page( using no frameworks as encouraged) since I thought the deadline is the end of the month. I thought I could change my application after submitting it :) I thought maybe I'll try spending some time building it.
Now nevermind I'll use this old page
Thanks for getting in touch and having a look, Dan

**Comment by sofer** [comment]
@iuliaL you can totally change it. No problem! I'll stop looking at this now and promise not to look again until next month :-)

**Comment by iuliaL** [comment]
You can look, heh you're funny.
Im not sure if I'll update it due to the lack of time. Thanks a lot. Cheers
